server:
  port: 8187

# Oracle Connect
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scottjpa
    password: tiger

  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
